### ISSUE TITLE
`gptel-extras-get-cost` use of `count-words`

### ISSUE THREAD

**Issue by tschwinge** [benthamite/dotfiles#8]
I stumbled over this in context of gptel <https://github.com/karthink/gptel/issues/315> "[enhancement] Provide information about the different models", thanks for that one, and the related PR!

(This is not included in the aforementioned gptel PR, but anyway) the use of `count-words` in `gptel-extras-get-cost`:

<https://github.com/benthamite/dotfiles/blob/276c0b0a40ac90e5bb6929bd4a365c1aa33c6ca5/emacs/extras/gptel-extras.el#L243-L252>

... is probably a non-negligible under-approximation of the actual LLM token count -- and should be noted as such in the doc-string?

For example, `count-words` for "\<A>, \<B>, \<C>, die Katze lief im Schnee." is eight, but LLM tokenizers (as far as I understand) would also count the punctuation characters and split up long words (so something like 15 tokens, here), plus the tokens representing the system message (so maybe a total of ~40 tokens, here), and any other context or directives if applicable.  

  - <https://docs.anthropic.com/en/docs/resources/glossary#tokens>
  - <https://platform.openai.com/tokenizer>

**Comment by benthamite** [comment]
Thanks for raising this! I was operating under the assumption that word count was a reasonable approximation of token count, but it seems my assumption was mistaken. I’ll take a closer look in the coming days and update the docstring or adjust the function.

**Comment by benthamite** [comment]
I have revised the function to add a 1.4 tokens/word conversion factor, which is what both Claude and GPT-4o suggested. I haven’t researched this more thoroughly, so if you think I should use a different number, please let me know.

The function still fails to handle other cases, notably when [including files or buffers as part of the context](https://github.com/karthink/gptel#include-more-context-with-requests).

**Comment by karthink** [comment]
> The function still fails to handle other cases, notably when [including files or buffers as part of the context](https://github.com/karthink/gptel#include-more-context-with-requests).

It's difficult to get a correct estimate without first building the full prompt that will be sent, which can be expensive if you have lots of context.  (Additionally, if any of the context is binary files, you'll have to base64-encode it first.)

**Comment by benthamite** [comment]
Yeah, I need to think about this a bit more. The possibility of including files/buffers for context also calls into question the idea of displaying this information in the modeling. Perhaps a better approach is to show it up somewhere in the `gptel` transient menu.

**Comment by benthamite** [comment]
[These](https://github.com/benthamite/dotfiles/commit/c3c421538345e3d41fd1a4b6e682e4dcd024b329) [two ](https://github.com/benthamite/dotfiles/commit/0c4d834c7abe7000ea5a86171e30d95004044e50) commits now include the context in the cost estimate and display the number of files, if any, included in the context. I find it useful to be reminded that files have been added to the context, since I mostly do not use the menu for sending the request and there is otherwise no visual feedback that this is the case.

<img width="846" alt="image" src="https://github.com/user-attachments/assets/19bc4ccb-7792-4354-a402-47650b5374c6">

**Comment by karthink** [comment]
@benthamite This looks nice.  Is the model name display in the modeline part of the `global-mode-string`?  BTW, gptel already provides a mode-line-version of its "live" header line for chat buffers via `gptel-use-header-line`, any idea if that works with doom-modeline?

**Comment by benthamite** [comment]
I actually moved the relevant parts of this to the gptel headerline recently, since it seemed like a more natural place for that information. The key was to make sure that this headerline was always active in gptel buffers, which I
accomplished as follows:

``` emacs-lisp
(defun gptel-extras-enable-gptel ()
  "Enable `gptel-mode' in `org-mode' files with `gptel' data."
  (when (and (derived-mode-p 'org-mode)
	     (cl-some (lambda (prop)
			(org-entry-get (point-min) prop))
		      ;; taken from `gptel-org--entry-properties'
		      '("GPTEL_SYSTEM" "GPTEL_BACKEND" "GPTEL_MODEL"
			"GPTEL_TEMPERATURE" "GPTEL_MAX_TOKENS"
			"GPTEL_NUM_MESSAGES_TO_SEND")))
    (let ((buffer-modified-p (buffer-modified-p)))
      (gptel-mode)
      ;; `breadcrumb-mode' interferes with the `gptel' header line
      (when (bound-and-true-p breadcrumb-mode)
	(breadcrumb-mode -1))
      ;; prevent the buffer from becoming modified merely because `gptel-mode'
      ;; is enabled
      (unless buffer-modified-p
	(save-buffer)))))
(add-hook 'org-mode-hook #'gptel-extras-enable-gptel)	
```

To display the relevant information in the headerline, I had to redefine `gptel-mode`:

```diff
  (define-minor-mode gptel-mode
!   "Minor mode for interacting with LLMs."
    :lighter " GPT"
    :keymap
    (let ((map (make-sparse-keymap)))
--- 1,7 ----
  (define-minor-mode gptel-mode
!   "Minor mode for interacting with LLMs.
! This is just the original `gptel-mode' definition with a modification
! to add an additional cost field in the header line."
    :lighter " GPT"
    :keymap
    (let ((map (make-sparse-keymap)))
***************
*** 30,35 ****
--- 32,43 ----
  				    (lambda (&rest _) (gptel-system-prompt)))
  				   'mouse-face 'highlight
  				   'help-echo "System message for session"))
+ 				 (cost
+ 				  (propertize
+ 				   (buttonize (format "[Cost: $%.2f]" (gptel-extras-get-cost))
+ 					      (lambda (&rest _) (gptel-menu)))
+ 				   'mouse-face 'highlight
+ 				   'help-echo "Cost of the current prompt"))
  				 (context
  				  (and gptel-context--alist
  				       (cl-loop for entry in gptel-context--alist
***************
*** 78,85 ****
  			     (propertize
  			      " " 'display
  			      `(space :align-to (- right ,(+ 5 (length model) (length system)
! 							     (length track-media) (length context)))))
! 			     track-media (and context " ") context " " system " "
  			     (propertize
  			      (buttonize (concat "[" model "]")
  					 (lambda (&rest _) (gptel-menu)))
--- 86,94 ----
  			     (propertize
  			      " " 'display
  			      `(space :align-to (- right ,(+ 5 (length model) (length system)
! 							     (length track-media) (length context) (length cost)))))
! 			     track-media (and context " ") context " " cost
! 			     " " system " "
  			     (propertize
  			      (buttonize (concat "[" model "]")
  					 (lambda (&rest _) (gptel-menu)))

```

The full code is [here](https://github.com/benthamite/dotfiles/blob/master/emacs/extras/gptel-extras.el#L55).

**Comment by benthamite** [comment]
The relevant functionality has now been moved to a [separate package](https://github.com/benthamite/gptel-plus).
